services:
  S3DedupProxy:
    container_name: s3dedupproxy_proxy
    image: s3dedupproxy_poolmgr
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "s3.lan:127.0.0.1"
      - "mastodon.s3.lan:127.0.0.1"
    depends_on:
      - Postgres
      - S3Proxy

  Postgres:
    container_name: s3dedupproxy_postgres
    image: postgres:17.2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=s3proxy
      - POSTGRES_PASSWORD=s3proxy
      - POSTGRES_DB=s3proxy

  S3Proxy:
    container_name: s3dedupproxy_s3proxy
    image: andrewgaul/s3proxy
    ports:
      - "8080:80"
    environment:
      - S3PROXY_AUTHORIZATION=none
